#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: fae1327
#
Name     : R-gplots
Version  : 3.1.3.1
Release  : 60
URL      : https://cran.r-project.org/src/contrib/gplots_3.1.3.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gplots_3.1.3.1.tar.gz
Summary  : Various R Programming Tools for Plotting Data
Group    : Development/Tools
License  : GPL-2.0
Requires: R-caTools
Requires: R-gtools
BuildRequires : R-caTools
BuildRequires : R-gtools
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
- calculating and plotting locally smoothed summary function as
    ('bandplot', 'wapply'),
  - enhanced versions of standard plots ('barplot2', 'boxplot2',
    'heatmap.2', 'smartlegend'),
  - manipulating colors ('col2hex', 'colorpanel', 'redgreen',
    'greenred', 'bluered', 'redblue', 'rich.colors'),
  - calculating and plotting two-dimensional data summaries ('ci2d',
    'hist2d'),
  - enhanced regression diagnostic plots ('lmplot2', 'residplot'),

%prep
%setup -q -n gplots
pushd ..
cp -a gplots buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706894186

%install
export SOURCE_DATE_EPOCH=1706894186
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gplots/ChangeLog
/usr/lib64/R/library/gplots/DESCRIPTION
/usr/lib64/R/library/gplots/INDEX
/usr/lib64/R/library/gplots/Meta/Rd.rds
/usr/lib64/R/library/gplots/Meta/data.rds
/usr/lib64/R/library/gplots/Meta/features.rds
/usr/lib64/R/library/gplots/Meta/hsearch.rds
/usr/lib64/R/library/gplots/Meta/links.rds
/usr/lib64/R/library/gplots/Meta/nsInfo.rds
/usr/lib64/R/library/gplots/Meta/package.rds
/usr/lib64/R/library/gplots/Meta/vignette.rds
/usr/lib64/R/library/gplots/NAMESPACE
/usr/lib64/R/library/gplots/NEWS
/usr/lib64/R/library/gplots/NEWS.md
/usr/lib64/R/library/gplots/R/gplots
/usr/lib64/R/library/gplots/R/gplots.rdb
/usr/lib64/R/library/gplots/R/gplots.rdx
/usr/lib64/R/library/gplots/TODO
/usr/lib64/R/library/gplots/data/rtPCR.rda
/usr/lib64/R/library/gplots/doc/index.html
/usr/lib64/R/library/gplots/doc/venn.R
/usr/lib64/R/library/gplots/doc/venn.Rnw
/usr/lib64/R/library/gplots/doc/venn.pdf
/usr/lib64/R/library/gplots/help/AnIndex
/usr/lib64/R/library/gplots/help/aliases.rds
/usr/lib64/R/library/gplots/help/gplots.rdb
/usr/lib64/R/library/gplots/help/gplots.rdx
/usr/lib64/R/library/gplots/help/paths.rds
/usr/lib64/R/library/gplots/html/00Index.html
/usr/lib64/R/library/gplots/html/R.css
/usr/lib64/R/library/gplots/tests/dat.csv
/usr/lib64/R/library/gplots/tests/heatmap2Test.R
/usr/lib64/R/library/gplots/tests/heatmap2Test.Rout.save
/usr/lib64/R/library/gplots/tests/heatmap_to_heatmap.2_test.R
/usr/lib64/R/library/gplots/tests/plotmeans_nobars.R
/usr/lib64/R/library/gplots/tests/test.reorder.factor.R
/usr/lib64/R/library/gplots/tests/test_plottingDeepDendrogram.R
